<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos_de_baloncesto [
<!ELEMENT equipos_de_baloncesto (equipo*)>
<!ELEMENT equipo (nombre, ciudad, entrenador, jugadores)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador (nombre, nacionalidad)>
<!ATTLIST jugador posicion (Base|Escolta|Alero|Pivot) #REQUIRED>
<!ELEMENT nacionalidad (#PCDATA)>
]> 

<equipos_de_baloncesto>
  <equipo>
    <nombre>Lakers</nombre>
    <ciudad>Los Angeles</ciudad>
    <entrenador>Frank Vogel</entrenador>
    <jugadores>
      <jugador posicion="Base">
        <nombre>Russell Westbrook</nombre>
        <nacionalidad>Estados Unidos</nacionalidad>
      </jugador>
      <jugador posicion="Alero">
        <nombre>LeBron James</nombre>
        <nacionalidad>Estados Unidos</nacionalidad>
      </jugador>
    </jugadores>
  </equipo>
  <equipo>
    <nombre>Heat</nombre>
    <ciudad>Miami</ciudad>
    <entrenador>Erik Spoelstra</entrenador>
    <jugadores>
      <jugador posicion="Base">
        <nombre>Kyle Lowry</nombre>
        <nacionalidad>Estados Unidos</nacionalidad>
      </jugador>
      <jugador posicion="Pivot">
        <nombre>Bam Adebayo</nombre>
        <nacionalidad>Estados Unidos</nacionalidad>
      </jugador>
    </jugadores>
  </equipo>
</equipos_de_baloncesto>
